### ISSUE TITLE
API returns nothing on country=br

### ISSUE THREAD

**Issue by GA114** [joshtronic/holidayapi.com#15]
[Well, this is embarrassing](http://holidayapi.com/v1/holidays?country=br&year=2015). :/ I wonder if I formatted my JSON poorly, although I assume that shouldn't. After I sent my [last pull request](https://github.com/joshtronic/holidayapi.com/pull/14), I removed the [trailing comma from the dataset](https://github.com/GA114/holidayapi.com/commit/df2d1fec2e6e9054cc0516f5cc6df637ced9a00e) in the hope that that would fix it, but... Anyway.

**Comment by joshtronic** [comment]
I'm an asshole, I should have tested it. I believe the PHP JSON implementation barks about the trailing commas. All merged in, looking good now.

Thanks dude!

**Comment by GA114** [comment]
A-whoops! My fault too for forgetting that comma. Remember to include that in the [Mturk documentation](https://github.com/joshtronic/holidayapi.com/issues/6) if that becomes a thing.
