### ISSUE TITLE
Unable to get working with PHP cURL

### ISSUE THREAD

**Issue by adampmoss** [joshtronic/holidayapi.com#42]
Great API, but not been able to get working with the most basic of PHP cURL requests:

    $ch = curl_init();
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_URL,"https://holidayapi.com/v1/holidays?country=GB&year=2016");
        $result=curl_exec($ch);
        curl_close($ch);
        
        var_dump($result);

If I use a different endpoint (e.g. http://api.fixer.io/2000-01-03) there's no problems. Can you explain this?

**Comment by joshtronic** [comment]
Your code worked fine for me... what's the error that you're receiving? (try dumping `curl_exec($ch)`)

I recently migrated DNS for the the service over to CloudFlare and added their SSL offering. Unsure if it's related to that.

**Comment by adampmoss** [comment]
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

Running locally through MAMP Pro

**Comment by adampmoss** [comment]
Just read this: http://blog.techstacks.com/2010/03/3-common-causes-of-unknown-ssl-protocol-errors-with-curl.html - SSL stuff is a bit over my head but it could be related to Cloudflare.

**Comment by joshtronic** [comment]
I went ahead and disabled the cloudflare SSL stuff, drop back to http:// and let me know if you continue to have any sort of problems. I'll revisit implementing SSL when I have the time to set up a real cert!!

**Comment by adampmoss** [comment]
That works fine now, thanks!
