### ISSUE TITLE
Banned by CloudFlare

### ISSUE THREAD

**Issue by raulium** [joshtronic/holidayapi.com#43]
I have a python script that queries your API no more than once a day, and today I received this message in return, stating that I've been banned.

```
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>
<title>Access denied | holidayapi.com used CloudFlare to restrict access</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />
<!--[if lt IE 9]><link rel="stylesheet" id=\'cf_styles-ie-css\' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->
<style type="text/css">body{margin:0;padding:0}</style>
<!--[if lte IE 9]><script type="text/javascript" src="/cdn-cgi/scripts/jquery.min.js"></script><![endif]-->
<!--[if gte IE 10]><!--><script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script><!--<![endif]-->
<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>

</head>
<body>
  <div id="cf-wrapper">
    <div class="cf-alert cf-alert-error cf-cookie-error" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>
    <div id="cf-error-details" class="cf-error-details-wrapper">
      <div class="cf-wrapper cf-header cf-error-overview">
        <h1>
          <span class="cf-error-type" data-translate="error">Error</span>
          <span class="cf-error-code">1010</span>
          <small class="heading-ray-id">Ray ID: 2708f2ed0af201ed &bull; 2016-02-06 18:34:24 UTC</small>
        </h1>
        <h2 class="cf-subheadline" data-translate="error_desc">Access denied</h2>
      </div><!-- /.header -->

      <section></section><!-- spacer -->

      <div class="cf-section cf-wrapper">
        <div class="cf-columns two">
          <div class="cf-column">
            <h2 data-translate="what_happened">What happened?</h2>
            <p>The owner of this website (holidayapi.com) has banned your access based on your browser\'s signature (2708f2ed0af201ed-ua48).</p>
          </div>

          
        </div>
      </div><!-- /.section -->

      <div class="cf-error-footer cf-wrapper">
  <p>
    <span class="cf-footer-item">CloudFlare Ray ID: <strong>2708f2ed0af201ed</strong></span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span data-translate="your_ip">Your IP</span>: 96.230.240.36</span>
    <span class="cf-footer-separator">&bull;</span>
    <span class="cf-footer-item"><span data-translate="performance_security_by">Performance &amp; security by</span> <a data-orig-proto="https" data-orig-ref="www.cloudflare.com/5xx-error-landing?utm_source=error_footer" id="brand_link" target="_blank">CloudFlare</a></span>
    
  </p>
</div><!-- /.error-footer -->


    </div><!-- /#cf-error-details -->
  </div><!-- /#cf-wrapper -->

  <script type="text/javascript">
  window._cf_translation = {};
  
  
</script>

</body>
</html>
```

**Comment by joshtronic** [comment]
I just flushed all of the banned IP's and disabled the firewall stuff, give it another go and let me know if it's working. Also, what's your script for / what's it do? Is it something that can be shared with the world??

**Comment by raulium** [comment]
Much appreciated.  However, I just checked and it still says that I'm being blocked based on my browser signature.  To get around it, I ended up using FancyURLopener in urllib to pass a chrome user-agent string (which worked).

The program I've made is just a glorified alarm clock at this point.  Based on some criterion, it determines if it should let me "sleep in" or not.  To "enrich" the experience, I've opted to wish me a happy <insert holiday name>; to wit, your API saved me countless hours of code writing.

I could share it, but definitely not in it's current state -- much too cobbled together. I'm in the process of re-writing it into a series of Apple-OSX-interaction libraries to make the code more manageable.

**Comment by joshtronic** [comment]
That sounds really cool!!!

Also wanted to follow up, is CF still giving you crap? It seems they only let me set the firewall to "essentially off" which IMHO isn't necessarily good enough, so if you're still experiencing a problem I'm going to move DNS to my domain provider and get out of CF entirely for this project.

I'm hoping it was perhaps cached on their end for a period of time and everything is g2g now.

**Comment by joshtronic** [comment]
2+ months w/o response. closing.

**Comment by raulium** [comment]
To be honest, ever since I started passing using a chrome user-agent in the GET request I stopped seeing an issue.  The issue probably centered around the fact that CF requires a user-agent string (declaring you're a web browser) as part of the web server configuration -- may not be something you can configure yourself.

As there was a work around, I didn't see much an issue.  If you need that documented, I could do that for you.

**Comment by joshtronic** [comment]
That's great to know. I'm going to do some testing on my end, if CF does in fact demand a UA to be set I'll be moving off of them for DNS as I don't feel that should be a requirement of this API

Thanks for following up!
