### ISSUE TITLE
Can't access from https

### ISSUE THREAD

**Issue by AndyBullivent** [joshtronic/holidayapi.com#50]
Hey, just a quick note that you can't access the api from within a js app that is running https (mixed content) would be nice if you could set up a https version of the site! (Although I understand that may cost you money, so may be a nope) :)

Don't need it for anything business critical, but was just developing a sample app on my company's platform (which is always https).

Cheers,
Andy

**Comment by joshtronic** [comment]
On my list :) I did the half-assed CF fake-SSL thing but it caused some issues. I'll try to get this worked out in the next week or so!

**Comment by AndyBullivent** [comment]
Thanks Josh! ☺

Andy

**Comment by wilerson** [comment]
Hi,

Any news about this?

**Comment by joshtronic** [comment]
Not yet @wilerson ... finally got my office setup, gonna set aside some time tomorrow evening to knock this out :)

**Comment by wilerson** [comment]
OK thanks. We will probably setup a server-side proxy on our side in the meanwhile. :)

**Comment by joshtronic** [comment]
Just got everything setup, now works via http and https 💥
