### ISSUE TITLE
Differentiate Between National Days and Statutory Holidays

### ISSUE THREAD

**Issue by matt-wilkinson** [joshtronic/holidayapi.com#55]
In the GB list of holidays it is difficult to find which ones are "Statutory" or Bank Holidays (there are 8 of these a year in the UK and are specified by the government https://www.gov.uk/bank-holidays) because there are many listed that are just occasions like Valentine's day (this is never a holiday in the UK). Could we have a new property to specify whether the holiday is "usually not-worked"

**Comment by joshtronic** [comment]
This is already being discussed in #54 and is on the roadmap with no ETA at this time

**Comment by matt-wilkinson** [comment]
#54 is subtly different because the uk list contains days that are *never* holidays (such as valentine's day, april fool's day, etc.) whereas in #54 those days are holidays but pertain to a subset of people or geographical area.

**Comment by joshtronic** [comment]
They both fall under the same changes that I am making to the API for v2. No need for me to have multiple open issues. If you look at the code I referenced in #54 you'll see the new data file layout that's in the works that I believe satisfies your request here (along with adding observance logic for holidays that occur on the weekends)
