### ISSUE TITLE
Multiple language support

### ISSUE THREAD

**Issue by joshtronic** [joshtronic/holidayapi.com#8]
My thought is to default the results to the native language of the country. Additionally you can pass in a language and receive the holidays in that language (if available).

**Comment by luisreyes** [comment]
Would this be using an external service to translate or does the api have the values in the languages requested?

**Comment by joshtronic** [comment]
Probably just have the languages baked into the JSON files themselves. A few ways to slice it though since it would probably make more sense to abstract the text out of the files and have language files outside of that (because Christmas can exist in multiple country files and would need a translation in each one).

As I type this out I am wondering if maintaining this project in the realm of these flat files is a horrible thing and that I should refocus around having a database and utilizing some basic normalization at that level.

**Comment by joshtronic** [comment]
Closing, creating milestone to address the action items that remain
